services:
  # Бэкенд
  backend:
    build: ./backend
    container_name: django_backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  # База данных
  db:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  # Фронтенд (Добавлен)
  frontend:
    build: ./frontend
    container_name: react_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules # Чтобы локальные node_modules не перезаписывали контейнерные
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data: